
module.exports = {
  ...require('./app-error'),
  ...require('./console-logger'),
  ...require('./get-json-from-file'),
  ...require('./get-random-int'),
  ...require('./hash-generator'),
  ...require('./html-string-replacer'),
  ...require('./is-error'),
  ...require('./is-object'),
  ...require('./is-string'),
  ...require('./register-babel'),
  ...require('./app-name'),
  ...require('./app-version'),
  ...require('./constants'),
  ...require('./file-hasher'),
  ...require('./file-system-extension'),
  ...require('./path-extension'),
  ...require('./hash-verifier'),
}
